settings:
  content:
    merge: true
media:
  input: media
  output: /img/silver-and-blood/guides/media
  extensions: [jpg, jpeg, png, gif, webp]
content:
  - name: characters
    label: Characters
    type: collection
    path: characters
    format: yaml
    filename: "{primary}.yaml"
    subfolders: false
    view:
      fields: [ id, name, rarity ]
      primary: slug
      sort: [ id, name ]
      default:
        search: ''
        sort: name
        order: desc
    fields:
      - name: id
        label: ID
        type: string
      - name: name
        label: Name
        type: string
      - name: slug
        label: Slug
        type: string
      - name: rarity
        label: Rarity
        type: select
        options:
          values: [ SSR+, SSR, SR ]
      - name: tags
        label: Tags
        type: string
        list: true