settings:
  content:
    merge: true
media:
  input: media
  output: /img/silver-and-blood/guides/media
  extensions: [jpg, jpeg, png, gif, webp]
content:
  - name: characters
    label: Characters
    type: collection
    path: characters
    format: yaml
    filename: "{primary}.yaml"
    subfolders: false
    view:
      fields: [ id, name, rarity ]
      primary: slug
      sort: [ id, name ]
      default:
        search: ''
        sort: name
        order: desc
    fields:
      - name: id
        label: ID
        type: string
      - name: name
        label: Name
        type: string
      - name: slug
        label: Slug
        type: string
      - name: rarity
        label: Rarity
        type: select
        options:
          values: [ SSR+, SSR, SR ]
      - name: tags
        label: Tags
        type: string
        list: true
  - name: teamComps
    label: Team Comps
    type: collection
    path: team-comps
    format: yaml
    filename: "{primary}.yaml"
    subfolders: false
    fields:
      - name: teamCompName
        label: Team Comp Name
        type: string
        required: true
      - name: teamMembers
        label: Team Members
        type: object
        list:
          collapsible: false
          min: 1
          max: 5
        required: true
        fields:
          - name: charName
            label: Char Name
            type: reference
            options:
              collection: characters
              search: "name"
              value: "{name}"
              label: "{name}"
            required: true
    view:
      fields: [ teamCompName ]
      primary: teamCompName
      sort: [ teamCompName ]
      default:
        search: ''
        sort: finalScore
        order: desc